---
title: "Baby Names"
author: "Prachi Naik"
date: "1/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(babynames)
library(tidyverse)

```
``` {r}

babynames %>% 
  filter(name == "Prachi") %>% 
  ggplot(aes(year, n)) + geom_col()

# restrict to just names that are top 1000 in the last year

topnames <- babynames %>% 
  filter(year == "2017") %>% 
  arrange(desc(n)) %>% 
  slice(1:1000)

# what preceptor did:

top_1000 <- babynames %>% 
  filter (year == max(year)) %>%  # this is so if you don't know that 2017 is the max
  group_by(name) %>%  # this is so male and female names are acknowledged and then set up for summing in next line
  summarise(total = sum (n)) %>%  #this is to add male and female occurrences of names
  arrange(desc(total)) %>% 
  slice (1:1000)

# use new top_1000 dataset to filter orig babynames dataset
smallerdata <- babynames[babynames$name %in% top_1000$name, ]

#how preceptor did it
babynames %>% 
  inner_join(top_1000, by = "name")

# the history of popularity of these 1000 names over time
smallerdata %>% 
  filter(name == "Mary") %>% 
  ggplot(aes(year, n)) + geom_line()


```
